export const data = [
    {
        "Email": 'sample@email.com',
        "Mother's Last Name": 'Griffin',
        "Mother's First Name": 'Lois',
        "Address": '123 Spooner Street',
        "Phone Number": '1231231234',
        "Referral Agency": 'Families For Families',
        "Number Of Children": 2,
        "Child Name(s)": ['Chris', 'Stewie'],
        "Child Gender(s)": ['Male', 'Male'],
        "Child Age(s)": ['15', '5'],
        "Child Grade(s)": ['8', '1'],
        "Date Signed Up": new Date().toLocaleDateString('en-US'),
        "Sponsor Email": 'marysmith@gmail.com', 
        "Sponsor Name": 'Mary Smith'        
    },
    {
        "Email": 'sample@email.com2',
        "Mother's Last Name": 'Griffin',
        "Mother's First Name": 'Lois',
        "Address": '123 Spooner Street2',
        "Phone Number": '12312312342',
        "Referral Agency": 'Families For Families2',
        "Number Of Children": 3,
        "Child Name(s)": ['Chris', 'Stewie', 'Meg'],
        "Child Gender(s)": ['Male', 'Male', 'Female'],
        "Child Age(s)": ['15', '2', '20'],
        "Child Grade(s)": ['8', 'Kindergarten', '11'],
        "Date Signed Up": new Date().toLocaleDateString('en-US'),
        "Sponsor Email": 'marysmithmsmdsfd@gmail.com', 
        "Sponsor Name": ''         
    },
    {
        "Email": 'sample@email.com',
        "Mother's Last Name": 'Griffin',
        "Mother's First Name": 'Peter',
        "Address": '123 Spooner Street',
        "Phone Number": '1231231234',
        "Referral Agency": 'Families For Families',
        "Number Of Children": 2,
        "Child Name(s)": ['Tommy', 'Stewie'],
        "Child Gender(s)": ['Male', 'Male'],
        "Child Age(s)": ['15', '5'],
        "Child Grade(s)": ['8', '1'],
        "Date Signed Up": new Date().toLocaleDateString('en-US'),
        "Sponsor Email": '', 
        "Sponsor Name": ''         
    },
    {
        "Email": 'sample@email.com',
        "Mother's Last Name": 'Griffin',
        "Mother's First Name": 'Lois',
        "Address": '123 Spooner Street',
        "Phone Number": '1231231234',
        "Referral Agency": 'Families For Families',
        "Number Of Children": 2,
        "Child Name(s)": ['Chris', 'Stewie'],
        "Child Gender(s)": ['Male', 'Male'],
        "Child Age(s)": ['15', '5'],
        "Child Grade(s)": ['8', '1'],
        "Date Signed Up": new Date().toLocaleDateString('en-US'),
        "Sponsor Email": '', 
        "Sponsor Name": ''        
    },
    {
        "Email": 'sample@email.com2',
        "Mother's Last Name": 'Griffin2',
        "Mother's First Name": 'Lois2',
        "Address": '123 Spooner Street2',
        "Phone Number": '12312312342',
        "Referral Agency": 'Families For Families2',
        "Number Of Children": 3,
        "Child Name(s)": ['Chris', 'Stewie2', 'Meg'],
        "Child Gender(s)": ['Male', 'Male2', 'Female'],
        "Child Age(s)": ['15', '52', '20'],
        "Child Grade(s)": ['8', '12', '11'],
        "Date Signed Up": new Date().toLocaleDateString('en-US'),
        "Sponsor Email": 'hahapetergriffin@yahoo.com', 
        "Sponsor Name": 'Peter Griffin'         
    },
    {
        "Email": 'sample@email.com',
        "Mother's Last Name": 'Griffin',
        "Mother's First Name": 'Peter',
        "Address": '123 Spooner Street',
        "Phone Number": '1231231234',
        "Referral Agency": 'Families For Families',
        "Number Of Children": 2,
        "Child Name(s)": ['Tommy', 'Stewie'],
        "Child Gender(s)": ['Male', 'Male'],
        "Child Age(s)": ['15', '5'],
        "Child Grade(s)": ['8', '1'],
        "Date Signed Up": new Date().toLocaleDateString('en-US'),
        "Sponsor Email": '', 
        "Sponsor Name": ''         
    }
]

